@startuml uc8
left to right direction
skinparam backgroundColor white
skinparam usecase {
    BackgroundColor White
    BorderColor #555555
    ArrowColor #555555
    FontSize 11
}
skinparam actor {
    BackgroundColor White
    BorderColor #555555
}

actor "Operatore" as op

rectangle "UC8 - Stima ATP per nuovo ordine" {
    (UC8\nStima ATP\nper nuovo ordine) as UC8
}

op --> UC8
@enduml
